# Generated by Django 3.2.9 on 2021-12-02 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='portfolios')),
                ('is_published', models.BooleanField(default=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('website_link', models.URLField(blank=True, max_length=250)),
                ('github_link', models.URLField(blank=True, max_length=350)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.skill')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
