# Generated by Django 3.2.9 on 2021-12-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='skill',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='skill',
            field=models.ManyToManyField(to='skill.Skill'),
        ),
    ]
