# Generated by Django 3.2.9 on 2021-12-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_library'),
        ('portfolio', '0002_auto_20211203_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='library',
            field=models.ManyToManyField(blank=True, null=True, to='skill.Library'),
        ),
    ]
