# Generated by Django 3.2.9 on 2021-12-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_library'),
        ('portfolio', '0004_portfolio_model_design_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='library',
            field=models.ManyToManyField(blank=True, to='skill.Library'),
        ),
    ]
